//Includes.
//Divide the patches in files for ease of maintenance.
INCLUDE ~%MOD_FOLDER%/components/%component%/lib/arcane/level1.tpa~
INCLUDE ~%MOD_FOLDER%/components/%component%/lib/arcane/level2.tpa~
INCLUDE ~%MOD_FOLDER%/components/%component%/lib/arcane/level3.tpa~
INCLUDE ~%MOD_FOLDER%/components/%component%/lib/divine/level1.tpa~
INCLUDE ~%MOD_FOLDER%/components/%component%/lib/divine/level2.tpa~
INCLUDE ~%MOD_FOLDER%/components/%component%/lib/divine/level3.tpa~